const sampleData = {
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Van Heusen Flex Collar Shirt',
      slug: 'van-heusen-flex-collar-shirt',
      category: "Men's Dress Shirts",
      description: 'Comfortable flex collar with a polished look',
      images: [
        '/images/sample-products/p7-1.jpg',
        '/images/sample-products/p7-2.jpg',
      ],
      price: 49.99,
      brand: 'Van Heusen',
      rating: 4.3,
      numReviews: 7,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Express Modern Fit Dress Shirt',
      slug: 'express-modern-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'Sleek and tailored for a modern silhouette',
      images: [
        '/images/sample-products/p8-1.jpg',
        '/images/sample-products/p8-2.jpg',
      ],
      price: 65.00,
      brand: 'Express',
      rating: 4.0,
      numReviews: 4,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Uniqlo Easy Care Shirt',
      slug: 'uniqlo-easy-care-shirt',
      category: "Men's Dress Shirts",
      description: 'Wrinkle-resistant and everyday-ready',
      images: [
        '/images/sample-products/p9-1.jpg',
        '/images/sample-products/p9-2.jpg',
      ],
      price: 29.90,
      brand: 'Uniqlo',
      rating: 3.9,
      numReviews: 15,
      stock: 12,
      isFeatured: true,
      banner: 'banner-3.jpg',
    },
    {
      name: 'Zara Premium Poplin Shirt',
      slug: 'zara-premium-poplin-shirt',
      category: "Men's Dress Shirts",
      description: 'Luxurious poplin fabric for a smart finish',
      images: [
        '/images/sample-products/p10-1.jpg',
        '/images/sample-products/p10-2.jpg',
      ],
      price: 59.50,
      brand: 'Zara',
      rating: 4.4,
      numReviews: 9,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'H&M Slim Fit Cotton Shirt',
      slug: 'hm-slim-fit-cotton-shirt',
      category: "Men's Dress Shirts",
      description: 'Slim and breathable cotton comfort',
      images: [
        '/images/sample-products/p11-1.jpg',
        '/images/sample-products/p11-2.jpg',
      ],
      price: 24.99,
      brand: 'H&M',
      rating: 3.8,
      numReviews: 6,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'J.Crew Ludlow Shirt',
      slug: 'jcrew-ludlow-shirt',
      category: "Men's Dress Shirts",
      description: 'Tailored Ludlow style with classic details',
      images: [
        '/images/sample-products/p12-1.jpg',
        '/images/sample-products/p12-2.jpg',
      ],
      price: 75.00,
      brand: 'J.Crew',
      rating: 4.6,
      numReviews: 14,
      stock: 3,
      isFeatured: true,
      banner: 'banner-4.jpg',
    },
    {
      name: 'Banana Republic Dress Shirt',
      slug: 'banana-republic-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'Refined shirt with modern elegance',
      images: [
        '/images/sample-products/p13-1.jpg',
        '/images/sample-products/p13-2.jpg',
      ],
      price: 89.95,
      brand: 'Banana Republic',
      rating: 4.1,
      numReviews: 10,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Dockers Easy Stretch Shirt',
      slug: 'dockers-easy-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Everyday shirt with stretch performance',
      images: [
        '/images/sample-products/p14-1.jpg',
        '/images/sample-products/p14-2.jpg',
      ],
      price: 44.50,
      brand: 'Dockers',
      rating: 3.7,
      numReviews: 6,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Gap Essential Oxford Shirt',
      slug: 'gap-essential-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Everyday classic with durable cotton',
      images: [
        '/images/sample-products/p15-1.jpg',
        '/images/sample-products/p15-2.jpg',
      ],
      price: 34.99,
      brand: 'Gap',
      rating: 4.0,
      numReviews: 11,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nordstrom Trim Fit Shirt',
      slug: 'nordstrom-trim-fit-shirt',
      category: "Men's Dress Shirts",
      description: 'Sharp trim fit with premium fabric',
      images: [
        '/images/sample-products/p16-1.jpg',
        '/images/sample-products/p16-2.jpg',
      ],
      price: 69.99,
      brand: 'Nordstrom',
      rating: 4.5,
      numReviews: 5,
      stock: 2,
      isFeatured: true,
      banner: 'banner-5.jpg',
    },
  ],
};

export default sampleData;
